services:
  - type: web
    name: inicjatywa-uchwalodawcza
    env: python
    buildCommand: ./build.sh
    startCommand: cd backend && gunicorn config.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: '2'

# databases section removed for staging to avoid free tier limits (sqllite fallback)

